WITH TRIPS AS(
select
RIDE_ID,
rideable_type,
DATE(TO_TIMESTAMP(STARTED_AT)) as TRIP_DATE,
START_STATIO_ID AS START_STATION_ID,
END_STATION_ID,
MEMBER_CSUAL AS MEMBER_CASUAL,
TIMESTAMPDIFF(SECOND, TO_TIMESTAMP(STARTED_AT),TO_TIMESTAMP(ENDED_AT)) AS TRIP_DURATION_SECONDS

from {{ source('demo', 'bike') }} 
where RIDE_ID != 'ride_id' 
limit 10
)

select 
*
from TRIPS